
== Overview

=== Safe Arithmetic Environment

The Safe Arithmetic library uses the C++ type system to encode and enforce
requirements on values. A special template type, `safe::var` is used to contain
these values.

```c++
namespaced safe {
    template<typename ValueType, auto Requirements>
    struct var;
}
```

Arithmetic, bitwise, and shift operators on `safe::var` values results in
the generation of a new `safe::var` with its requirements updated to represent
the set of possible values the result may contain. Operations on `safe::var`
values are guaranteed to be safe at compile-time. There is no runtime overhead
incurred. Only the desired operations are performed.

Operations on instances of `safe::var` forms a hermetically sealed context in
which overflows, underflows, and division-by-zero are proven impossible by
the Safe Arithmetic library implementation. If such a condition were possible
due to an arithmetic operation on a `safe::var`, then compilation would fail.

This leaves two important questions, how to get values in and out of this "Safe
Arithmetic Environment".

=== Creating Safe Values

Safe literal values can be created using the `_i` user defined literal. It will
create a `safe::var` with the necessary integer type to contain the value and
a requirement that matches the value. Literal values larger than 64-bits are
implemented using an arbitrary precision integer type built into the Safe
Arithmetic library.

```c++
namespace safe::literals {
    template <char... chars>
    constexpr auto operator""_i();
}
```

Safe versions of the C++ primitive integer types are available for declaring
runtime values. Each primitive integer type is wrapped in `safe::var` with a
requirement describing the range of that primitive type.

```c++
namespace safe {
    // safe versions of C++ primitive integer types
    using u8 = var<std::uint8_t, ...>;
    using s8 = var<std::int8_t, ...>;
    using u16 = var<std::uint16_t, ...>;
    using s16 = var<std::int16_t, ...>;
    using u32 = var<std::uint32_t, ...>;
    using s32 = var<std::int32_t, ...>;
    using u64 = var<std::uint64_t, ...>;
    using s64 = var<std::int64_t, ...>;
}
```

Because each safe primitive integer type requirement's can contain all values
that are representable by the underlying type, it is safe to directly assign
primitive values to instances of these safe primitive types.

```c++
// SAFE: The signed literal value is gauranteed to fit in a std::int64_t.
safe::s64 foo = 0xc001bea7;

// COMPILE ERROR: On systems with 32- or 64-bit int types, the literal will be
// too large to fit and compilation will fail.
safe::s16 bar_1 = 0xba11;

// SAFE: The safe integer UDL encodes its requirements in its type, the value
// is known at compile-time to fit in bar_2.
safe::s16 bar_2 = 0x5a5_i;

// SAFE: A safe 64-bit int can represent all values in an unsigned safe 16-bit int.
foo = bar_1;

// SAFE: A safe 32-bit unsigned int can safely be assigned the value of a uint32_t
volatile std::uint32_t my_fav_reg;
safe::u32 safe_reg_val = my_fav_reg;

// SAFE: Masking safe_reg_val by an 8-bit value guarantees the result will fit
// in a safe::u8
safe::u8 safe_reg_field_val_1 = safe_reg_val & 0xFF_i;

// COMPILE ERROR: safe::u8 cannot represent all possible values of these rhs
// variables.
safe::u8 safe_reg_field_val_2 = safe_reg_val;
safe::u8 safe_reg_field_val_3 = my_fav_reg;
```

For integer values that cannot fit in the primitive types provided by C++, the
Safe Arithmetic library provides an arbitrary precision implementation,
`safe::integer`.

```c++
namespace safe {
    // safe arbitrary precision signed integer type
    template<std::size_t NumBits>
    using integer = var<...>;
}
```

Safe Arithmetic's integer promotion rules will automatically pick an integer
type large enough to represent the possible values of an arithmetic operation.
There is little need to explicitly use `safe::integer`.

```c++
auto big_int_value = 0xba5eball'd00d5a7e'a11f00d5'900d900b_i;

// SAFE: The result of the operation is known at compile time to fit.
safe::u64 small_1 = big_int_value >> 64_i;

// COMPILE ERROR: The result cannot be represented by a uint64_t.
safe::u64 small_2 = big_int_value >> 32_i;

volatile safe::u64 hw_reg_1;
volatile safe::u64 hw_reg_2;

// SAFE: The result type is automatically promoted to a safe::integer<66>. The
// 66th bit is the two's complement sign bit and the 65th bit is the carry from
// the 64-bit addition.
auto reg_result = hw_reg_1 + hw_reg_2;

// COMPILE ERROR: The addition of these unchecked values could overflow a
// safe:u64.
safe::u64 reg_result_2 = hw_reg_1 + hw_reg2;

// SAFE: The result is explicitly being masked to 64-bits.
safe::u64 reg_result_3 = (hw_reg_1 + hw_reg2) & 0xFFFF'FFFF'FFFF'FFFF_i;
```


`safe::match` is the only mechanism in the Safe Arithmetic library that will
produce additional runtime overhead. It creates a callable object that may be
called with `safe::var` or naked integer values. It uses compile-time checks
if possible to match the given arguments with the `matchable_funcs` arguments.
If compile-time checks are not possible for an argument, then the value is
checked at runtime to determine if it satisfies the requirements for one of the
`matchable_funcs`. It is analogous to a pattern matching switch statement where
the `matchable_funcs` arguments `safe::var` requirements are the patterns to
match the callable object's input arguments against.

This is the recommended way of marshalling external integer values into a safe
arithmetic environment when the valid values are a subset of the underlying
integer type's range. For example, an external value arrives in a full 16-bit
unsigned integer, but the valid values are only 0 through 50,000. The full
16 bits are needed to represent the value, but only a subset of the 16-bit
integer range is valid.

```c++
// Pseudo C++20 to illustrate safe::match API
template <typename F, typename Return, std::size_t NumArgs>
concept Callable = requires(F f, auto... args) {
    Return retval = f(args...);
    requires sizeof...(args) == NumArgs;
};

namespace safe {
    template<typename Return, std::size_t NumArgs>
    Callable<Return, NumArgs> auto match(
        Callable<Return, NumArgs> auto... matchable_funcs,
        Callable<Return, 0> auto default_func
    );
}
```

The operation of `safe::match` is easier to understand with some examples.

```c++
// Hardware register reporting a count of some event type.
volatile std::uint32_t event_counter_hw_reg;

// Hardware register representing the event type being reported.
volatile std::uint32_t event_type_hw_reg;

// Firmware array keeping track of updated event counts.
safe::array<safe::u16, 17> event_counts{};

constexpr auto process_event_count = safe::match(
    [](
        safe::ival_u32<0, 1023> event_count,
        safe::ival_u32<0, 16> event_type
    ){
        auto const prev_count = event_counts[event_type];
        auto const new_count = prev_count + event_count;

        // this example is making the implementation choice of saturating the
        // event count to prevent overflow and rollover.
        event_counts[event_type] = max(new_count, std::numeric_limits<safe::u16>::max());
    },

    // Multiple functions with different requirements for parameters may be
    // passed in. The first function whose argument requirements are satisified
    // by the runtime argument values is executed. The last function must be
    // the default handler and is only executed if no prior match is found.

    [](){
        // default action, handle error condition as desired
    }
);

// Hardware triggers this interrupt every time a new event count is ready to
// be processed.
void event_count_interrupt_handler() {
    process_event_count(event_counter_hw_reg, event_type_hw_reg);
}
```

`safe::match` is a powerful tool that is discussed in more detail in the
reference section.

The final method of introducing values into the safe arithmetic environment is
through `unsafe_cast<T>(value)`. It bypasses all compile-time and runtime
safety checks and depends on the value to be proven to satisfy the requirements
of `T` using mechanisms outside the visibility and scope of the Safe Arithmetic
library. Its use is highly discouraged. The name is chosen to cause an uneasy
feeling in programmers and clearly signal a red flag for code reviewers.

```c++
template<typename T>
T unsafe_cast(auto value);
```

`unsafe_cast<T>(value)` is used within the Safe Arithmetic library to ferry
values into instances of `safe::var` after proving it is safe to do so. It is
necessary for the library's construction.

As always, an example is useful to illustrate how to use a particular function.

```c++
std::uint16_t some_function();
void do_something_useful(safe::ival_u32<0, 1024> useful_value);

// VERY DANGEROUS: Don't do this!
auto dangerous_value = unsafe_cast<safe::ival_u32<0, 1024>>(some_function());
do_something_useful(dangerous_value);

// SAFE: Use safe::match instead. This will only call 'do_something_useful'
// if the result of 'some_function' satisfies the requirements on
// 'useful_value'. If it doesn't match, the default callable will be invoked.
safe::match<void>(do_something_useful, [](){})(some_function());

// SAFE: Don't use unsafe_cast<T>(value), try almost everything else first.
```

If you find a case where you feel you must use `unsafe_cast`, then maybe there
is a gap in the Safe Arithmetic API or an algorithm that is missing. Please let
us know by filing an issue.

=== Extracting Safe Values

Extracting values out of the safe arithmetic environment is not dangerous or
unsafe in itself, but it is important to be explicit when doing so.
`safe_cast<T>(value)` is used to extract integer values out of `safe::vars`.
It is an acknowledgement by the programmer they are leaving the safe
environment and must now take on the burden of ensuring safe arithmetic
operations manually. It is also a clear indication for code reviewers to take a
more critical look at any following integer operations.

```c++
template<typename T>
T safe_cast(auto value);

safe::ival_s32<-1000, 1000> my_safe_value = 42_i;

// SAFE: It's OK to use safe_cast to assign to a wider primitive type
auto innocent_value = safe_cast<std::int32_t>(my_safe_value);

// COMPILE ERROR: A narrowing conversion is not allowed by safe_cast
auto another_innocent = safe_cast<std::int8_t>(my_safe_value);
```


=== Safe Arithmetic Requirements DSL

The Requirements Domain-Specific Language is used to define the set of valid
values for a `safe::var<T, Requirements>` templated type. `safe_numerics` and
`bounded::integer` both use interval arithmetic at compile time to track the
set of valid values. The Safe Arithmetic library works with intervals, sets,
tristate bitmasks, and set operators like union, intersection, and difference
to define arbitrary requirements on values. Just like `safe_numerics` and
`bounded::integer`, it will calculate the new set of possible values for any
arithmetic, bitwise, or shift operation.

Since interval requirements are commonly used, there are convenience types for
creating them:

```c++
safe::ival_s32<-100, 100> small_number{};
```

Which is equivalent to the following:

```c++
safe::var<std::int32_t, safe::ival<-100, 100>> small_number = 0_i;
```

If we want to exclude '0' from the range, the DSL allows us to do that:

```c++
using safe::ival;
safe::var<std::int32_t, ival<-100, -1> || ival<1, 100>> small_nonzero_number = 1_i;
```

This enables the library to protect against divide-by-zero at compile-time. The
division operator function arguments require the divisor to be non-zero.

```c++
// COMPILE ERROR: small_number _might_ be zero
auto result_1 = 10_i / small_number;

// SAFE: small_nonzero_number is guaranteed to be non-zero.
auto result_2 = 10_i / small_nonzero_number;
```

The DSL can be used by itself, outside of `safe::var`. This can be helpful to
illustrate the rules and capabilities of the DSL itself.

The assignment operator and constructors for `safe::var<T, Req>` that accept
another `safe::var<RhsT, RhsReq>` use set inequality operators to determine
whether it is safe or not. The right-hand-side argument's requirements must
be a subset of the left-hand-side target.

```c++
using safe::ival;

constexpr auto non_zero_req = ival<-100, -1> || ival<1, 100>;
constexpr auto small_num_req = ival<-100, 100>;

// The `<=` operator is used for 'is subset of'
static_assert(non_zero_req <= small_num_req);

safe::var<std:int32_t, non_zero_req> non_zero = 1_i;

// The `<=` operator ensures this assignment is safe at compile-time
safe::var<std::int32_t, small_num_req> small_num = non_zero;
```

When any operation is performed on a `safe::var` instance, the mirror operation
is performed on the requirements.

```c++
using safe::ival;

constexpr auto one_to_ten_req = ival<1, 10>;
constexpr auto non_zero_req = ival<-100, -1> || ival<1, 100>;

safe::var<std:int32_t, non_zero_req> a = 42_i;
safe::var<std:int32_t, one_to_ten_req> b = 3_i;

auto c = a * b;

// runtime value is updated as expected
assert(c == 126_i);

// static requirements are also updated as expected
static_assert(c.requirement == ival<-1000, -1> || ival<1, 1000>);
```

==== Requirement DSL Primitives

|===
|Name |Definition |{cpp} | Description

|Interval
|stem:[[a, b]]
| ```safe::ival<a, b>```
| A set of values from a to b, inclusive.

|Set
|stem:[{a, b, c, ...}]
| ```safe::set<a, b, c, ...>```
| A set of explicitly defined values.

|Mask
|
stem:[{x in NN \| 0 <= x < 2^n ^^ (x\ \&\ ~V) = C))}]

| ```safe::mask<V, C>```
| V is the variable bits mask. C is the constant bits mask. `safe::mask`
produces a set of integers where the binary digits match C if the corresponding
digits of V are unset. The binary digit places that are set in V are
unconstrained in the elements of the produced set.

|===


==== Requirement DSL Operators

|===
|Name |Definition |{cpp} Operator | Description

|Subset
|stem:[A subseteq B]
| ```A {lt}= B```
| Test if A is a subset of B.

|Superset
|stem:[A supe B]
| ```A >= B```
| Test if A is a superset of B.

|Set Equality
|stem:[A = B]
| ```A == B```
| Test if A and B contain identical elements.

|Set Inequality
|stem:[A != B]
| ```A != B```
| Test if A and B do not contain identical elements.

|Set Union
|stem:[A uu B]
| ```A \|\| B```
| Set of all elements in A and B.

|Set Intersection
|stem:[A nn B]
| ```A && B```
| Set of common elements in A and B.

|Addition
|stem:[{a + b \| a in A, b in B}]
|```A + B```
| Set of product pairs of A and B added.

|Subtraction
|stem:[{a - b \| a in A, b in B}]
|```A - B```
| Set of product pairs of A and B subtracted.

|Multiplication
|stem:[{a * b \| a in A, b in B}]
|```A * B```
| Set of product pairs of A and B multiplied.

|Division
|stem:[{a / b \| a in A, b in B}]
|```A / B```
| Set of product pairs of A and B divided.

|Modulo
|stem:[{a % b \| a in A, b in B}]
|```A % B```
| Set of product pairs of A and B modulo.

|Absolute Value
|stem:[{\|a\| \| a in A}]
|```abs(A)```
| Set of the absolute value of all elements in A.

|Minimum Value
|stem:[{min(a, b) \| a in A, b in B}]
|```min(A, B)```
| Set of the minimum of each product pair of A and B.

|Maximum Value
|stem:[{max(a, b) \| a in A, b in B}]
|```max(A, B)```
| Set of the maximum of each product pair of A and B.

|Bitwise AND
|stem:[{a\ &\ b \| a in A, b in B}]
|```A & B```
| Set of product pairs of A and B bitwise ANDed.

|Bitwise OR
|stem:[{a \| b \ \|\ a in A, b in B}]
|```A \| B```
| Set of product pairs of A and B bitwise ORed.

|Bitwise XOR
|stem:[{a\ o+\ b \| a in A, b in B}]
|```A ^ B```
| Set of product pairs of A and B bitwise XORed.

|Bitwise NOT
|stem:[{~a \| a in A}]
|```~A```
| Bitwise NOT of all elements in A.

|Bitwise Shift Left
|stem:[{a " << " b \| a in A, b in B}]
|```A << B```
| Set of product pairs of A and B bitwise shifted left.

|Bitwise Shift Right
|stem:[{a " >> " b \| a in A, b in B}]
|```A >> B```
| Set of product pairs of A and B bitwise shifted right.
|===

