
== API Reference

=== safe::var

```c++
namespace safe {
    template<typename T, auto Requirement>
    struct var;
}
```

`safe::var` wraps a runtime value with an associated `safe::dsl` requirement
describing the set of values it must be contained in. The requirement is used
to check the value at runtime or prove at compile-time it is satisfied.

==== Member constants

===== `requirement`

The `safe::dsl` requirement describing allowed values.

==== Member functions

===== Constructor

```c++
constexpr var() requires(requirement >= set<0>);
```

Default constructor, only valid if the requirement allows a value of '0'.

```c++
constexpr var(Var auto const & rhs);
```

Construct a `safe::var` from another instance with potentially different,
but compatible requirements. Assignment safety is checked at compile time.

===== operator=

```c++
constexpr auto operator=(Var auto & rhs) -> var &;
```

Assign value from another instance with potentially different, but compatible
requirements. Assignment safety is checked at compile time.

==== Non-member functions

===== operator{lt}={gt}

```c++
[[nodiscard]] constexpr auto operator<=>(Var auto lhs, Var auto rhs) -> std::strong_ordering;
```

Apply `operator{lt}={gt}` to `lhs` and `rhs` and return the result.

===== operator==

```c++
[[nodiscard]] constexpr auto operator==(Var auto lhs, Var auto rhs) -> bool;
```

Apply `operator==` to `lhs` and `rhs` and return the result.

===== operator+

```c++
[[nodiscard]] constexpr auto operator+(Var auto lhs, Var auto rhs);
```

Add the underlying values of `lhs` and `rhs` and return the result.

Value types are promoted to a wider type if the result would otherwise
overflow or underflow. No wraparound for signed or unsigned types.

Value types are demoted to a narrower type, down to the natural word size of
the underlying architecture, if all possible results will fit.

===== operator-

```c++
[[nodiscard]] constexpr auto operator-(Var auto lhs, Var auto rhs);
```

Subtract the underlying values of `lhs` and `rhs` and return the result.

Value types are promoted to a wider type if the result would otherwise
overflow or underflow. No wraparound for signed or unsigned types.

Value types are demoted to a narrower type, down to the natural word size of
the underlying architecture, if all possible results will fit.

```c++
[[nodiscard]] constexpr auto operator-(Var auto v);
```

Equivalent to `0_i - v`.

===== operator*

```c++
[[nodiscard]] constexpr auto operator*(Var auto lhs, Var auto rhs);
```

Multiply the underlying values of `lhs` and `rhs` and return the result.

Value types are promoted to a wider type if the result would otherwise
overflow or underflow. No wraparound for signed or unsigned types.

===== operator/

```c++
[[nodiscard]] constexpr auto operator/(Var auto lhs, Var auto rhs);
```

Divide the underlying values of `lhs` and `rhs` and return the result.

Value types are demoted to a narrower type, down to the natural word size of
the underlying architecture, if all possible results will fit.

[WARNING]
====
A compilation error will result if the `rhs` requirement doesn't exclude '0'.
====

===== operator%

```c++
[[nodiscard]] constexpr auto operator%(Var auto lhs, Var auto rhs);
```

Modulo the underlying values of `lhs` and `rhs` and return the result.

Value types are demoted to a narrower type, down to the natural word size of
the underlying architecture, if all possible results will fit.

[WARNING]
====
A compilation error will result if the `rhs` requirement doesn't exclude '0'.
====

===== operator<<

```c++
[[nodiscard]] constexpr auto operator<<(Var auto lhs, Var auto rhs);
```

Shift `lhs` left by `rhs` bit positions and return the result.

Value types are promoted to a wider type if the result would otherwise
overflow or underflow. No wraparound for signed or unsigned types.

[NOTE]
====
Unlike built in `operator<<`, shifting by greater than the width `lhs` is
defined behavior. The resulting type will be promoted to an integer large
enough to represent the value.
====

===== operator>>

```c++
[[nodiscard]] constexpr auto operator>>(Var auto lhs, Var auto rhs);
```

Shift `lhs` right by `rhs` bit positions and return the result.

Value types are demoted to a narrower type, down to the natural word size of
the underlying architecture, if all possible results will fit.

[WARNING]
====
A compilation error will result if the `rhs` requirement doesn't exclude
all negative numbers or numbers larger than the bit width of `lhs`.
====

===== operator|

```c++
[[nodiscard]] constexpr auto operator|(Var auto lhs, Var auto rhs);
```

Bitwise OR the underlying values of `lhs` and `rhs` and return the result.

The resulting value type is the wider type of `lhs` and `rhs`.

===== operator&

```c++
[[nodiscard]] constexpr auto operator&(Var auto lhs, Var auto rhs);
```

Bitwise AND the underlying values of `lhs` and `rhs` and return the result.

The resulting value type is the narrower type of `lhs` and `rhs`.

===== operator^

```c++
[[nodiscard]] constexpr auto operator^(Var auto lhs, Var auto rhs);
```

Bitwise XOR the underlying values of `lhs` and `rhs` and return the result.

The resulting value type is the wider type of `lhs` and `rhs`.

===== abs

```c++
[[nodiscard]] constexpr auto abs(Var auto v);
```

Calculate the absolute value of `v` and return the result.

===== bit_width

```c++
[[nodiscard]] constexpr auto bit_width(Var auto v);
```

Calculate the bit width of `v` and return the result.

Value types are demoted to a narrower type, down to the natural word size of
the underlying architecture, if all possible results will fit.

===== min

```c++
[[nodiscard]] constexpr auto min(Var auto lhs, Var auto rhs);
```

Calculate the minimum of `lhs` and `rhs` and return the result.

The resulting value type is the narrower type of `lhs` and `rhs`.

===== max

```c++
[[nodiscard]] constexpr auto max(Var auto lhs, Var auto rhs);
```

Calculate the maximum of `lhs` and `rhs` and return the result.

The resulting value type is the wider type of `lhs` and `rhs`.

===== clamp

```c++
[[nodiscard]] constexpr auto clamp(
    Var auto value,
    Var auto min_val,
    Var auto max_val
);
```

Clamps `value` from `min_val` to `max_val` and return the result.

The resulting value type is the underlying type of `max_val`.

```c++
[[nodiscard]] constexpr auto clamp(
    auto unsafe_value,
    Var auto min_val,
    Var auto max_val
);
```

Clamps `value` from `min_val` to `max_val` and return the result.

The resulting value type is the underlying type of `max_val`.


=== `safe::dsl`

===== operator==

```c++
[[nodiscard]] constexpr auto operator==(auto A, auto B) -> bool;
```

stem:[A = B]

Return true if the set of numbers represented by the requirements `A` and
`B` contain exactly the same numbers.

===== operator!=

```c++
[[nodiscard]] constexpr auto operator!=(auto A, auto B) -> bool;
```

stem:[A != B]

Return true if the set of numbers represented by the requirements `A` and
`B` contain at least one different number.

===== operator{lt}=

```c++
[[nodiscard]] constexpr auto operator<=(auto A, auto B) -> bool;
```

stem:[A subseteq B]

Return true if the set of numbers represented by the requirement `rhs` contains
all the numbers `lhs` does.

===== operator{gt}=

```c++
[[nodiscard]] constexpr auto operator>=(auto A, auto B) -> bool;
```

stem:[A supe B]

Return true if the set of numbers represented by the requirement `lhs` contains
all the numbers `rhs` does.

===== operator||

```c++
[[nodiscard]] constexpr auto operator||(auto A, auto B) -> bool;
```

stem:[A uu B]

===== operator&&

```c++
[[nodiscard]] constexpr auto operator&&(auto A, auto B) -> bool;
```

stem:[A nn B]

===== operator+

```c++
[[nodiscard]] constexpr auto operator+(auto A, auto B);
```

stem:[{a + b \| a in A, b in B}]

===== operator-

```c++
[[nodiscard]] constexpr auto operator-(auto A, auto B);
```

stem:[{a - b \| a in A, b in B}]

===== operator*

```c++
[[nodiscard]] constexpr auto operator*(auto A, auto B);
```

stem:[{a * b \| a in A, b in B}]

===== operator/

```c++
[[nodiscard]] constexpr auto operator/(auto A, auto B);
```

stem:[{a / b \| a in A, b in B}]

[WARNING]
====
A compilation error will result if the `rhs` requirement doesn't exclude '0'.
====

===== operator%

```c++
[[nodiscard]] constexpr auto operator/(auto A, auto B);
```

stem:[{a % b \| a in A, b in B}]

[WARNING]
====
A compilation error will result if the `rhs` requirement doesn't exclude '0'.
====

===== abs

```c++
[[nodiscard]] constexpr auto abs(auto A);
```

stem:[{\|a\| \| a in A}]

===== min

```c++
[[nodiscard]] constexpr auto min(auto A, auto B);
```

stem:[{min(a, b) \| a in A, b in B}]

===== max

```c++
[[nodiscard]] constexpr auto max(auto A, auto B);
```

stem:[{max(a, b) \| a in A, b in B}]

===== operator&

```c++
[[nodiscard]] constexpr auto operator&(auto A, auto B);
```

stem:[{a\ &\ b \| a in A, b in B}]

===== operator|

```c++
[[nodiscard]] constexpr auto operator|(auto A, auto B);
```

stem:[{a \| b \ \|\ a in A, b in B}]

===== operator^

```c++
[[nodiscard]] constexpr auto operator^(auto A, auto B);
```

stem:[{a\ o+\ b \| a in A, b in B}]

===== operator~

```c++
[[nodiscard]] constexpr auto operator~(auto A);
```

stem:[{~a \| a in A}]

===== operator<<

```c++
[[nodiscard]] constexpr auto operator<<(auto A, auto B);
```

stem:[{a " << " b \| a in A, b in B}]

===== operator>>

```c++
[[nodiscard]] constexpr auto operator>>(auto A, auto B);
```

stem:[{a " >> " b \| a in A, b in B}]




=== safe::array

```c++
namespace safe {
    template<typename T, std::size_t Size>
    struct array;
}
```

`safe::array` is a thin wrapper around `std::array`. It adds the ability to
check `operator[](pos)` and `at(pos)` access at compile-time. It does not
perform any checks at runtime and should otherwise be equivalent to 
`std::array`.


==== Member functions

Member functions are same as `std::array` with the following exceptions:

1. No C++ exceptions will be thrown by any member function.
2. `data()` is intentionally omitted.
3. `operator[](pos)` and `at(pos)` have different signatures to support indexing by 
   `safe:var`.

Only member functions significantly different from `std::array` are documented
here.

===== operator[]

```c++
constexpr auto operator[](var<size_type, ival<0, Size - 1>> pos) -> reference;
constexpr auto operator[](var<size_type, ival<0, Size - 1>> pos) const -> const_reference;
```

Access element at `pos`. The value of `pos` must be proven to be within the
range of the array at compile-time.

===== at

```c++
constexpr auto at(var<size_type, ival<0, Size - 1>> pos) -> reference;
constexpr auto at(var<size_type, ival<0, Size - 1>> pos) const -> const_reference;
```

Identical to `operator[]`. Access element at `pos`. The value of `pos` must be
proven to be within the range of the array at compile-time.


=== safe::match

Use runtime checking to safely encapsulate values into `safe::var`s. 
Automatically infer `safe::var` return type from multiple possible
return values.

==== Examples

===== Interpreting ASCII character as hexadecimal

Without Safe Arithmetic, interpreting an ASCII character as hexadecimal may
look something like the following code.

```c++
auto char_to_ord = [](auto digit){
    if ('0' <= digit && digit <= '9') {
        return digit - '0';

    } else if ('a' <= digit && digit <= 'f') {
        return digit - 'a' - 10;

    } else if ('A' <= digit && digit <= 'F') {
        return digit - 'A' - 10;

    } else {
        return 0;
    }
};
```

Refactoring this code to use the Safe Arithmetic library is straight-forward 
using the `safe::match` function.

```c++
auto char_to_ord = safe::match(
    [](ival_s32<'0', '9'> dec_digit){
        return dec_digit - s32_<'0'>;
    }, 
    [](ival_s32<'a', 'f'> lower_hex_digit){
        return lower_hex_digit - s32_<'a'> + 10_s32;
    },
    [](ival_s32<'A', 'F'> upper_hex_digit){
        return upper_hex_digit - s32_<'A'> + 10_s32;
    },
    [](){
        return 0_s32;
    }
);
```

This implementation ensures the return type of `char_to_ord` is 
`ival_s32<0, 15>`. This minimal interval was automatically calculated by
`safe::match`. This is the power of `safe::match`: check runtime values are 
within a specified set of values, wrap the values in the corresponding 
`safe::var` type, and optionally return a value whose `safe::var` requirement
is the union of the possible values from each branch.


=== Algorithms

==== safe::irange

```c++
namespace safe {
    template<typename BeginT, typename EndT>
    struct irange;
}
```

Similar to boost `irange` and Python's `range`. An iterable range of 
`safe::var` integers.

===== Discussion

A drawback of Safe Arithmetic's compile-time checking strategy is apparent 
when attempting to increment a `safe::var`. Adding `1` to a value could risk
overflow, and so it results in a compilation error. 

There are some ways around this depending on the specific situation:

1. Use `safe::clamp` to restrict the result.
2. If wraparound is acceptable, use `operator%`.
3. Use `safe::match` to conditionally assign the result.

For a simple `for` loop, these options are not useful. `safe::irange` should be
used instead to iterate over a series of integers with a `safe::var` index 
value.

===== Example

```c++
// can only be indexed with safe values
safe::array<safe::s32, 10> values{};

// A bare for-loop will not work. See above discussion for explanation.
// for (safe::ival_s32<0, 9> i = 0_s32; i < 10_s32; i = i + 1_s32) {
//     :'(
// }

for (auto i : safe::irange(0_s32, 10_s32)) {
    // 'i' is proven to be one of 0 through 9...
    static_assert(std::is_same_v<decltype(i), safe::ival_s32<0, 9>>);

    // ...therefore it can be used to index a safe::array
    values[i] = 0;
}
```

==== safe::accumulate

```c++
namespace safe {
    template<
        size_t max_iter,
        typename IterType,
        typename ValueType,
        typename Op>
    requires (
        std::input_iterator<IterType> &&
        std::is_same_v<std::iterator_traits<IterType>::value_type, ValueType> &&
        std::regular_invocable<Op, ValueType, ValueType> &&
        Var<ValueType>)
    constexpr auto accumulate(
        IterType first, 
        IterType last, 
        ValueType init = ValueType{}, 
        Op op = std::plus{});

    template<
        size_t max_iter,
        typename RangeType,
        typename ValueType,
        typename Op>
    requires (
        std::ranges::range<RangeType> &&
        std::is_same_v<std::ranges::range_value_t<RangeType>, ValueType> &&
        std::regular_invocable<Op, ValueType, ValueType> &&
        Var<ValueType>)
    constexpr auto accumulate(
        RangeType && range, 
        ValueType init = ValueType{}, 
        Op op = std::plus{});
}
```

Works like `std::accumulate`, with the following exceptions:

1. Only works with ranges of `safe::var`s.
2. Runtime execution of the function will stop when either the end of the range
   is reached, or `max_iter` is reached.
3. The return type is a `safe::var` with the largest possible interval based on
   the type contained in the range and the `max_iter` value.

==== safe::reduce

Works like `std::reduce`, with the following exceptions:

1. Only works with ranges of `safe::var`s.
2. Runtime execution of the function will stop when either the end of the range
   is reached, or `max_iter` is reached.
3. The return type is a `safe::var` with the largest possible interval based on
   the type contained in the range and the `max_iter` value.
4. The operation over the value type must satisfy the `safe::Associative` and 
   `safe::Commutative` concepts.

```c++
namespace safe {
    template<
        size_t max_iter,
        typename IterType,
        typename ValueType,
        typename Op>
    requires (
        std::input_iterator<IterType> &&
        std::is_same_v<std::iterator_traits<IterType>::value_type, ValueType> &&
        std::regular_invocable<Op, ValueType, ValueType> &&
        Var<ValueType> &&
        Associative<Op, ValueType> &&
        Commutative<Op, ValueType>)
    constexpr auto reduce(
        IterType first, 
        IterType last, 
        ValueType init = ValueType{}, 
        Op op = std::plus{});

    template<
        size_t max_iter,
        typename RangeType,
        typename ValueType,
        typename Op>
    requires (
        std::ranges::range<RangeType> &&
        std::is_same_v<std::ranges::range_value_t<RangeType>, ValueType> &&
        std::regular_invocable<Op, ValueType, ValueType> &&
        Var<ValueType> &&
        Associative<Op, ValueType> &&
        Commutative<Op, ValueType>)
    constexpr auto reduce(
        RangeType && range, 
        ValueType init = ValueType{}, 
        Op op = std::plus{});

    template<
        size_t max_iter,
        typename ExecutionPolicy,
        typename IterType,
        typename ValueType,
        typename Op>
    requires (
        std::is_execution_policy_v<ExecutionPolicy> &&
        std::input_iterator<IterType> &&
        std::is_same_v<std::iterator_traits<IterType>::value_type, ValueType> &&
        std::regular_invocable<Op, ValueType, ValueType> &&
        Var<ValueType> &&
        Associative<Op, ValueType> &&
        Commutative<Op, ValueType>)
    auto reduce(
        ExecutionPolicy && policy,
        IterType first, 
        IterType last, 
        ValueType init = ValueType{}, 
        Op op = std::plus{});

    template<
        size_t max_iter,
        typename ExecutionPolicy,
        typename RangeType,
        typename ValueType,
        typename Op>
    requires (
        std::is_execution_policy_v<ExecutionPolicy> &&
        std::ranges::range<RangeType> &&
        std::is_same_v<std::ranges::range_value_t<RangeType>, ValueType> &&
        std::regular_invocable<Op, ValueType, ValueType> &&
        Var<ValueType> &&
        Associative<Op, ValueType> &&
        Commutative<Op, ValueType>)
    auto reduce(
        ExecutionPolicy && policy,
        RangeType && range, 
        ValueType init = ValueType{}, 
        Op op = std::plus{});
}
```




