== Arbitrary Precision Integers

=== Introduction to safe::big_integer

There are a couple uses for an arbitrary precision `big_integer`:

1. They are convenient to use when calculating bounds at compile-time.
2. They can be helpful to use at runtime for values exceeding standard C++20
   integer widths.

While they are useful, both the API and design must be carefully considered in
order to minimize compile-time and runtime performance impacts and arithmetic
correctness with respect to overflow and underflow conditions.

In order to meet these basic requirements, the following design rules
are selected:

1. No dynamic memory allocation. Integer types will be represented by a type
   templated by its bit width.
2. Specialized integer promotion rules. The return type of an operation
   _should_ be wide enough to represent any result without overflow or
   underflow.
3. No C++ exceptions. Exceptional conditions will not be handled by
   `big_integer`. For user code, `big_integer` should always be wrapped in a
   `safe::var` to provide protection from unsafe operations.
4. `big_integer` shall be signed and there will be no unsigned version.
5. Seamless interop with standard integral types.


=== Examples



=== Design

The `big_integer` type is implemented in two major components:

1. `detail::storage` contains the low-level implementation of the integer 
   representation and operations. Results are returned through reference 
   parameters. This is done to decouple result bit-width from the operation
   implementation.
2. `interface::big_integer` contains the outward-facing interface of 
   `big_integer`. It has implementations for the integral operators and behaves
   much like a regular integral type. 

Concepts are used to ensure the operator functions have at least one 
`big_integer` parameter while the other parameter could be a built-in integral
type, `std::integral_constant`, or another `big_integer`.

Almost all operations return a `big_integer` wide enough for the result without
overflow or underflow. The exception is `operator<<`, which may overflow when
given a runtime value. If `operator<<` is given a `std::integral_constant`
shift amount, then the resulting type will be widened by the size of the shift
amount. In that case, no overflow or underflow is possible.